<script src="{{ asset('theme_one/js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('theme_one/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('theme_one/js/bootstrap.min4.3.1.js') }}"></script>
<script src="{{ asset('theme_one/js/jquery.flexslider.js') }}"></script>
<script src="{{ asset('theme_one/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('theme_one/js/custom-gallery.js') }}"></script>
<script src="{{ asset('theme_one/js/custom-navigation.js') }}"></script>
<script src="{{ asset('theme_one/vendors/gijgo-combined-1.9.13/js/gijgo.min.js') }}"></script>
<script src="{{ asset('theme_one/js/custom-flex.js') }}"></script>
<script src="{{ asset('theme_one/js/custom-owl.js') }}"></script>
<script src="{{asset('/datetime/build/jquery.datetimepicker.full.min.js')}}"></script>